yatube_project/posts/urls.py
from django.urls import path
from . import views

app_name = "posts"

urlpatterns = [
    path('group/<slug:slug>/', views.group_post, name='group_list'),
    path('', views.index, name='index'),
]

yatube_project/yatube_project/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
]

yatube_project/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

class Group(models.Model):
    title = models.CharField(
        max_length=200,
        verbose_name='Название группы',
        help_text='Введите понятное название группы'
    )
    slug = models.SlugField(
        max_length=150,
        unique=True,
        verbose_name='Адрес группы',
        help_text='Введите slug группы. (Будет использован для генерации url)'
    )
    description = models.TextField(
        verbose_name='Описание группы',
        help_text='Добавьте описание группы'
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'

class Post(models.Model):
    objects = models.Manager()
    text = models.TextField(
        verbose_name='Содержание поста',
        help_text='Укажите понятное содержание поста'
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации',
        help_text='Выберите дату публикации (по умолчанию текущая дата/время)'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа для поста',
        help_text='Группа, к которой относиться пост. (может быть пустой)'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор поста',
        help_text='Автор из таблицы User'
    )




    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'
        ordering = ('pub_date',)
        get_latest_by = 'pub_date'

yatube_project/posts/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Group
from django.http import HttpResponse


def index(request):
    templates = "posts/index.html"
    posts = Post.objects.order_by('-pub_date'[:10])
    title = "Это главная страница проекта Yatube"
    context = {'title': title,
               'posts': posts}
    return render(request, templates, context)


def group_post(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = Post.objects.filter(group=group).order_by('-pub_date')[:10]
    context = {'group': group,
               'posts': posts}
    return render(request, 'posts/group_list.html', context)

yatube_project/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="{% static 'img/fav/fav.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180"
          href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32"
          href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16"
          href="{% static 'img/fav/favicon-16x16.png' %}">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>Последние обновления на сайте</title>
</head>
<body>
<header>
    {% include 'includes/header.html' %}
</header>
<main>
    {% block content %}
    {% endblock %}
</main>
<footer>
    {% include 'includes/footer.html' %}
</footer>
</body>
</html>

yatube_project/templates/includes/footer.html
<footer class="border-top text-center py-3">
    <p>© 2020 Copyright <span style="color:red">Ya</span>tube</p>
</footer>

yatube_project/templates/includes/header.html
{% load static %}
<nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
        <a class="navbar-brand" href="{% url 'posts:index' %}">
            <img src="{% static 'img/logo.png' %}" width="30" height="30"
                 class="d-inline-block align-top" alt="">
            <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
            <span style="color:red">Ya</span>tube</a>
        </a>
    </div>
</nav>

yatube_project/templates/posts/group_list.html
{% extends "base.html" %}
{% block title %} Записи сообщества {{ group_post.title }}{% endblock %}
{% block header %} Записи сообщества {{ group.title }}{% endblock %}
{% block content %}
<h1> {{ group.title }} </h1>
<p> {{ group.description }} </p>

{% for post in posts %}
<h3>Автор: {{ post.author.get_full_name }},
    Дата публикации: {{ post.pub_date|date:"d E Y" }}</h3>
<p>{{ post.text|linebreaksbr }}</p>
{% if not forloop.last %}
<hr>
{% endif %}
{% if post.group %}
  <a href="#">Все записи группы</a>
{% endif %}
{% endfor %}
{% endblock %}}

yatube_project/templates/posts/index.html
{% extends "base.html" %}
{% block title %}Последние обновления на сайте{% endblock %}

{% block content %}
<div class="container py-5">
    <h1>Последние обновления на сайте</h1>
    <article>
        {% for post in posts %}
        <ul>
            <li>
                Автор: {{ post.author.get_full_name }}
            </li>
            <li>
                Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
        </ul>
        <p>{{ post.text }}</p>
        {% if post.group %}
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
        {% endif %}

        {% if not forloop.last %}
        <hr>
        {% endif %}
        {% endfor %}
    </article>
</div>
{% endblock %}